---
include:
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.134/gitlab-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.134/terraform-toolkit.yml"

stages:
  - test
  - release

validate-terraform:
  extends: .validate-terraform
  parallel:
    matrix:
      - TF_DIR: ["."]

validate-readme:
  extends: .validate-readme

release:
  extends: .release